"""Zero-based column indices for the final A:BY annotation worksheet."""

TITLE = 0
KEYWORDS = 2
JOURNAL = 3
PUBLICATION_YEAR = 4

ASD_N = 12
ASD_LABEL = 13
ASD_AGE_RANGE = 14
ASD_MEAN_AGE = 15
ASD_SD_AGE = 16
ASD_MALE = 17
ASD_ASSESSMENT = 18
ASD_OTHER_ASSESSMENT = 19
ASD_COMORBIDITIES = 20

NEUROTYPICAL_N = 21
NEUROTYPICAL_LABEL = 22
NEUROTYPICAL_AGE_RANGE = 23
NEUROTYPICAL_MEAN_AGE = 24
NEUROTYPICAL_SD_AGE = 25
NEUROTYPICAL_MALE = 26

OTHER_DIAGNOSIS_N = 30
OTHER_DIAGNOSIS_LABEL = 31
OTHER_DIAGNOSIS_AGE_RANGE = 32
OTHER_DIAGNOSIS_MEAN_AGE = 33
OTHER_DIAGNOSIS_SD_AGE = 34
OTHER_DIAGNOSIS_MALE = 35

GAZE = 40
SPEECH = 41
MOTOR = 42
OTHER_BEHAVIORAL = 43
OTHER_DATA = 44
FEATURE_FUSION = 45
ALGORITHMS = 46
FEATURES = 47
LEARNING_TYPE = 48
EVALUATION_METRICS = 49
BEST_MODEL = 50
BEST_PERFORMANCE = 51
FEATURE_IMPORTANCE_TECHNIQUE = 52
FEATURE_IMPORTANCE_RESULT = 53
BALANCING_TECHNIQUE = 54
CROSS_CORPUS_VALIDATION = 55
XFOLD_CV = 56
LOXO = 57
REAL_TIME_ANALYSIS = 58
STUDY_SETTING = 59
STUDY_GOAL = 60
NEW_DATASET = 61
DATASET_NAME = 62
DATA_OPEN_SOURCE = 63
LONGITUDINAL_TIME = 65
DATA_COLLECTION_TOOL = 66
PARTICIPANT_TASK = 67
CODE_OPEN_SOURCE = 68
STUDY_LIMITATIONS = 69
MAIN_FINDINGS = 71
BIDS_STRUCTURE = 72
NOVEL_ANALYSIS_PIPELINE = 73
FUTURE_RESEARCH_PIPELINES = 74
SENSITIVE_DATA = 75
SENSITIVE_DATA_PROTECTION = 76
